# Generated by Django 5.0.2 on 2024-03-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_body_comment_content_remove_comment_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
