# Generated by Django 5.0.3 on 2024-03-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_comment_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tags',
        ),
        migrations.AddField(
            model_name='news',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
